# Generated by Django 5.0.6 on 2024-06-09 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='', max_length=100)),
                ('restaurant_address', models.CharField(default='', max_length=100)),
                ('restaurant_description', models.CharField(default='', max_length=1024)),
                ('staff_count', models.IntegerField(default=0)),
                ('manager_count', models.IntegerField(default=0)),
                ('waiter_count', models.IntegerField(default=0)),
                ('admin_count', models.IntegerField(default=0)),
                ('totalEarn', models.FloatField(default=0)),
                ('totalCost', models.FloatField(default=0)),
                ('Monthly_earn', models.FloatField(default=0)),
                ('Monthly_cost', models.FloatField(default=0)),
                ('Yearly_earn', models.FloatField(default=0)),
                ('Yearly_cost', models.FloatField(default=0)),
                ('Most_selling_item', models.CharField(default='', max_length=100)),
                ('Monthly_profit', models.FloatField(default=0)),
                ('Yearly_profit', models.FloatField(default=0)),
                ('totalPayable', models.FloatField(default=0)),
                ('openingDate', models.DateField(auto_now_add=True)),
                ('closingDate', models.DateField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ownerName',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='restaurantAddress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='restaurantName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totalBal',
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_waiter',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
        migrations.AddField(
            model_name='user',
            name='connectedRestaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Restaurant', to='accounts.restaurant'),
        ),
    ]
