# Generated by Django 5.0.6 on 2024-08-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_restaurant_rename_ownername_user_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='totalPayable',
            new_name='DayUsed',
        ),
    ]
